### ISSUE TITLE
gzip option

### ISSUE THREAD

**Issue by ht2** [ishanjain28/s3-mongo-backup#5]
You could consider adding the gzip option to the dump command - would make for a smaller data transfer back up to S3 (and of course reduced storage costs).

https://docs.mongodb.com/manual/reference/program/mongodump/#cmdoption-gzip

**Comment by ishanjain28** [comment]
Sure. I can do that. But isn't zip more efficient than gzip? 
I also tried this to verify. 

- Dump a database to a folder.
- Zip it

And, 

- Create an Archive of database using `--archive` option. 

zipped database was smaller in size compared to archive.

**Comment by ishanjain28** [comment]
@ht2 You are right. I tried it with more databases of varying size and `mongodump`'s `--archive` option coupled with `--gzip` option creates smaller files.
And using these options instead of seperate modules makes everything much more simple, So I removed `rimraf` and `zip-folder`. 

Thank you so much for your suggestion. Please let me know if there is anything else you would like to see. 

Regards 
Ishan Jain

**Comment by ht2** [comment]
No problem! I'm working a lot with Mongo and transfers of data at the moment so was interested to see you create this library. Certainly a library or option to go back the other way (`mongorestore`) will prove useful for people I'm sure. Just remember that when you mongorestore with a gzip'd dump you have to specify the `--gzip` flag on the way back up too :)

**Comment by ishanjain28** [comment]
Sure. I'll start working on it.

**Comment by ishanjain28** [comment]
@ht2, I figured, this might be of some use to you, I published a new module that helps in restoring backups from s3. It's [here](https://npm.im/s3-mongo-restore)
